---
- name: Install firewalld package
  yum: pkg=firewalld state=present

- name: Ensure firewalld is running and enabled on boot
  service: name=firewalld state=started enabled=yes

- name: Add firewalld rules for services from vars
  firewalld:
    service={{ item.service }}
    zone={{ item.zone | default ("public") }}
    permanent={{ item.permanent | default (True) }}
    state={{ item.state | default ("enabled") }}
  with_items: "{{ firewalld_allow_services }}"
  notify: firewalld reload
- name: Add firewalld rules for ports from vars
  firewalld:
    port={{ item.port }}
    zone={{ item.zone | default ("public") }}
    permanent={{ item.permanent | default (True) }}
    state={{ item.state | default ("enabled") }}
  with_items: "{{ firewalld_allow_ports }}"
  notify: firewalld reload
